---
output: html_document
title: metabolomic - paper
---

## Initialization with data
### Read the data from the excel sheet

```{r}
library(readxl)
data <- read_excel(
    "../Input/Datenbank_Steroide_gruppiert_230421.xlsx",
    skip = 1, sheet = "Steroids", col_names = TRUE)
```

```{r}
library(dplyr)

dat1 <- data.frame(data, row.names = data$"Pat.-Nr.")

# Remove the Pat.-Nr., Sex and the Age
dat1 <- dat1 %>% select(-1, -2, -3)
``` 

### Removing non applicable data points
```{r}
# Function to Remove all 'NA' from the data
replacezero <- function(x) "[<-"(x, !x | is.na(x), min(x[x > 0],na.rm = TRUE) / 2)

# apply the function to our data, renaming it to 'dat2' in the process
dat2 <- as.data.frame(t(apply(dat1, 1, replacezero)))


sum(is.na(dat2))
```

## Transform data to logarithmic with base 2

```{r}
logdata <- log(dat2, 2)

# Function for pareto scaling
paretoscale <- function(z) {
  rowmean <- apply(z, 1, mean) # row means
  rowsd <- apply(z, 1, sd)  # row standard deviation
  rowsqrtsd <- sqrt(rowsd) # sqrt of sd
  rv <- sweep(z, 1, rowmean,"-")  # mean center
  rv <- sweep(rv, 1, rowsqrtsd, "/")  # dividing by sqrtsd
  return(rv)
}

# Pareto scale log transformed data
logdata.pareto <- scale(paretoscale(logdata))

boxplot(logdata.pareto)
```

## Principal Component analysis

```{r}
pca <- prcomp(logdata.pareto, center=F, scale=F)

# Display

plot(pca)
biplot(pca)

# Make a simple scores plot
plot(pca$x[,1], pca$x[,2], type='p', cex=0, pch=20, main="Scores Plot", xlab="PC1", ylab="PC2")
text(pca$x[,1], pca$x[,2], labels=rownames(pca$x), cex=1.0)
abline(h=0, v=0, col="red")

# Make a simple loadings plot (variance among variables)
plot(pca$rotation[,1], pca$rotation[,2], type='p', cex=0.5, pch=20,main="Loadings Plot", xlab="PC1", ylab="PC2")
abline(h=0, v=0, col="red")
```

```{r}
# Create a container called "results" for PCA results
results <- summary(pca)

names(results)

# Extract PCA results into data frames

scree.data <- as.data.frame(results$importance)
score.data <- as.data.frame(results$x)
loadings.data <- as.data.frame(results$rotation)

plot(loadings.data$PC1, loadings.data$PC2)
pvalue <- 0.09
abline(v=pvalue, col="red")
abline(v=-pvalue, col="red")
abline(h=pvalue, col="red")
abline(h=-pvalue, col="red")

# Make a new data frame with PC1, PC2, and PC3 loadings
loadings.PC1.PC2 <- loadings.data[,1:3]
loadings.PC1.PC2[1:6,1:3]  # look at the first few rows

# subset significant loadings
loadings.sig <- subset(loadings.PC1.PC2,
                       PC1 > pvalue | PC1 < -pvalue |
                         PC2 > pvalue | PC2 < -pvalue)

# sanity check - plot the results
plot(loadings.sig$PC1, loadings.sig$PC2)

# logdata.pareto.subset <- subset(logdata.pareto, rownames(logdata.pareto) %in% rownames(loadings.sig))
```

```{r}
####################################################
# Heatmaps
####################################################

library(gplots)
heatmap.2(as.matrix(logdata.pareto), cexRow=0.5, cexCol=0.5 )

```

## Clustering

```{r}
library(factoextra)
library(cluster)
library(ggplot2)

gap_stat <- clusGap(t(logdata.pareto),
                    FUN = kmeans,
                    K.max = 5)

fviz_gap_stat(gap_stat)

result <- (clara(logdata.pareto, 5))

fviz_cluster(result, data = logdata.pareto)

```

```{r}
is.data.frame(logdata.pareto)
```

```{r}
library(tibble)
clustered_data <- as.data.frame(logdata.pareto) %>% add_column(cluster = result$clustering)
```

```{r}
for (cluster in unique(clustered_data$cluster)) {
  boxplot(clustered_data[clustered_data$cluster == cluster,], main=cluster)
}
```

```{r}

median_cluster <- list()
for (cluster in unique(clustered_data$cluster)) {
  median_cluster[[cluster]] <- apply(clustered_data[clustered_data$cluster == cluster, ], 2, median)
} 
```

```{r}
line_colors <- c("blue", "red", "green")
new_color <- function(x) {
  return(line_colors[[(x %% length(line_colors))+1]])
}
```

```{r}
plot(unlist(median_cluster[[1]][1:30]), 
    type = "l", xlab = "metabolites", ylab = "concentration",
    ylim=c(-1, 1),
    main = "Median Cluster", xaxt = "n", col=new_color(1))

axis(1, at = 1:30, labels=rownames(as.data.frame(median_cluster[[1]][1:30])))

for (cluster in 2:length(median_cluster)) {
  lines(unlist(median_cluster[[cluster]][1:30]), col=new_color(cluster))
}

legend("topright", legend = 1:length(median_cluster), col = line_colors, lwd = 2)
```

## Add Ratios
```{r}
ratios <- function(y) {
  df <- data.frame(matrix(nrow = 357, ncol =0))

  df$relative_overall_androgen_production_1 <- apply(y, 1, \(x) {return((x["An"] + x["Et"]) / (x["a.THF"] + x["THF"] + x["THE"]))})
  df$relative_overall_androgen_production_2 <- apply(y, 1, \(x) {return((x["An"] + x["Et"] + x["A5.3b.17a"] + x["A5.3b.17b"] + x["DHEA"] + x["X16a.OH.DHEA"] + x["A5T.16a"]) / (x["a.THF"] + x["THF"] + x["THE"]))})
  
  df$relative_adrenal_androgen_production_1 <- apply(y, 1, \(x) {return((x["DHEA"]) / (x["a.THF"] + x["THF"] + x["THE"]))})
  df$relative_adrenal_androgen_production_2 <- apply(y, 1, \(x) {return((x["DHEA"] + x["X16a.OH.DHEA"] + x["A5T.16a"])/(x["a.THF"] + x["THF"] + x["THE"]))})
  
  df$relative_overproduction_of_3bHSD_1 <- apply(y, 1, \(x) {return(x["DHEA"] / (x["An"] + x["Et"]))})
  df$relative_overproduction_of_3bHSD_2 <- apply(y, 1, \(x) {return((x["DHEA"] + x["X16a.OH.DHEA"] + x["A5T.16a"]) / (x["An"] + x["Et"]))})
  df$relative_overproduction_of_3bHSD_3 <- apply(y, 1, \(x) {return((x["DHEA"] + x["X16a.OH.DHEA"] + x["A5T.16a"]) / (x["a.THF"] + x["THE"] + x["THF"]))})
  df$relative_overproduction_of_3bHSD_4 <- apply(y, 1, \(x) {return(x["P5T.17a"] / (x["a.THF"] + x["THF"] + x["THE"]))})
  df$relative_overproduction_of_3bHSD_5 <- apply(y, 1, \(x) {return(x["P5T.17a"] / x["PT"])})

  df$X21_hydroxylase_activity_1 <- apply(y, 1, \(x) {return((x["PT"] + x["Po.5b.3a"] + x["Po.5a.3a"]) / (x["a.THF"] + x["THF"] + x["THE"]))})
  df$X21_hydroxylase_activity_2 <- apply(y, 1, \(x) {return((x["X11.O.Pt"] + x["PT"] + x["Po.5b.3a"] + x["Po.5a.3a"]) / (x["a.THF"] + x["THF"] + x["THE"]))})
  df$X21_hydroxylase_activity_3 <- apply(y, 1, \(x) {return((x["X11.O.Pt"]) / (x["a.THF"] + x["THF"] + x["THE"]))})
  df$X21_hydroxylase_activity_4 <- apply(y, 1, \(x) {return(x["X11.O.Pt"] / x["a.Cl"])})

  df$X11b_hydroxylase_activity_1 <- apply(y, 1, \(x) {return(x["THS"] / (x["a.THF"] + x["THF"] + x["THE"]))})
  df$X11b_hydroxylase_activity_2 <- apply(y, 1, \(x) {return((x["An"] + x["Et"]) / (x["X11.OH.An"] + x["X11.OH.Et"]))})

  df$X17_hydroxylase_activity_global <- apply(y, 1, \(x) {return((x["THA"] + x["THB"] + x["a.THB"]) / (x["An"] + x["Et"]))})
  df$X17_hydroxylase_activity_17a_hydroxylase_activity_d5 <- apply(y, 1, \(x) {return(x["P5D"] / x["P5T.17a"])})
  df$X17_hydroxylase_activity_17a_hydroxylase_activity_d4 <- apply(y, 1, \(x) {return(x["PD"] / x["PT"])})
  df$X17_hydroxylase_activity_17a_hydroxylase_activity_global <- apply(y, 1, \(x) {return((x["a.THF"] + x["THF"] + x["THE"]) / (x["An"] + x["Et"]))})

  return(df)
}
```

```{r}
combined_df <- cbind(clustered_data, ratios(clustered_data))

heatmap(as.matrix(combined_df[,33:50]))
```

```{r}
median_cluster <- list()
for (cluster in unique(combined_df$cluster)) {
  median_cluster[[cluster]] <- apply(combined_df[combined_df$cluster == cluster, ], 2, median)
} 
```

```{r}
plot(unlist(median_cluster[[1]][33:50]), 
    type = "l", xlab = "metabolites", ylab = "concentration",
    ylim=c(-1, 1),
    main = "Median Ratios For Clusters", xaxt = "n", col=new_color(1))

axis(1, at = 33:50, labels=rownames(as.data.frame(median_cluster[[1]][33:50])))

for (cluster in 2:length(median_cluster)) {
  lines(unlist(median_cluster[[cluster]][33:50]), col=new_color(cluster))
}

legend("topright", legend = 1:length(median_cluster), col = line_colors, lwd = 2)
```