name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Nix
      run: curl -L https://nixos.org/nix/install | sh
      env:
        NIX_PATH: nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixpkgs-unstable.tar.gz
    
    - name: Setup Nix
      run: . /home/runner/.nix-profile/etc/profile.d/nix.sh

    - name: Activate Nix flakes
      run: nix build
